name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees:
  -
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true
